### ISSUE TITLE
2-way dense layer in code and paper seems mismatch.

### ISSUE THREAD

**Issue by WongKinYiu** [Robert-JunWang/Pelee#71]
In the paper, figure 1 (a).
The output of branch $a$ and branch $b$ are: {2k, k/2} and {2k, k/2, k/2}.

In the prototxt.
The output of branch $a$ and branch $b$ of stage $1$ are: {k/2, k/2} and {k/2, k/2, k/2}.
The output of branch $a$ and branch $b$ of stage $2$ are: {k/2, k/4} and {k/2, k/4, k/4}.
The output of branch $a$ and branch $b$ of stage $3$ are: {k/2, k/8} and {k/2, k/8, k/8}.
The output of branch $a$ and branch $b$ of stage $4$ are: {k/4, k/16} and {k/4, k/16, k/16}.

I would like to know which one can get the results in the paper, thank you.

**Comment by Robert-JunWang** [comment]
The result in the paper is based on the architecture of that prototxt. Since PeleeNet uses the different bottleneck width in the different stage, the figure is drawn based on 4x growth rate to make it is easier to compare to the original DenseNet. But I think the output that you described above is a little different from the prototxt file. For each branch, It should be {k/2, k/2} in stage 1, {k, k/2} in stage 2, and {2k, k/2} in stage 3 and stage 4.

**Comment by WongKinYiu** [comment]
thanks for your answer.
in my description, i assume k has different value in different stages. (stage1: k=32; stage2: k=64, ...)
