### ISSUE TITLE
MAX v.s. AVE Pooling

### ISSUE THREAD

**Issue by chienyiwang** [Robert-JunWang/Pelee#8]
Hi Robert,

I noticed that you have commented out line 80 in peleenet.py file, which is the max pooling layer replacing the original average pooling layer. Could you share your experience on the performance difference between the two options? Thank you!

**Comment by Robert-JunWang** [comment]
I just tried max pooling at the very beginning of the project and did not compare the performance of these two models in detail. At that time, the model with ave pooling achieved a slightly higher accuracy than the one with max pooling on Stanford Dogs dataset. For the object detection task, the model with max pooling is slightly better than the one with ave pooling. But that object detection model was trained from scratch, instead of initializing with the model pre-trained on ImageNet, and the model was not fully convergent at that time.

**Comment by chienyiwang** [comment]
@Robert-JunWang , Thanks for the experience sharing. I will also post my findings if there is any interesting results.

**Comment by ujsyehao** [comment]
I found in Densenet network, it uses max pooling after first conv layer, but then uses 2x2 average pooling in each transition layer, average pooling is rarely used in object detection method.
